---
driver:
  name: vagrant

provisioner:
  name: chef_zero

# Uncomment the following verifier to leverage Inspec instead of Busser (the
# default verifier)
# verifier:
#   name: inspec

platforms:
  - name: windows-2012r2
    driver_config:
      box: chef/windows-server-2012r2-standard

suites:
  - name: default
    run_list:
      - recipe[mingw::default]
    attributes:
      mingw:
        path32: C:/mingw32
        path64: C:/mingw64
